### ISSUE TITLE
boot into a non-root user without login

### ISSUE THREAD

**Issue by samrose** [Holo-Host/nixpkgs#13]

**Comment by gavinrogers** [comment]
Title:    boot into a non-root user without login
Author:   samrose
State:    open
Posted:   Mon Jul 16 18:29:11 2018
Labels:   in progress

Body
There's nothing here!

Comments:
There's nothing here!

**Comment by samrose** [comment]
I actually have this one tackled, code is forthcoming

**Comment by samrose** [comment]
closing supereceded by #15
