### ISSUE TITLE
split hydra build into fork of upstream + custom channels to build iso

### ISSUE THREAD

**Issue by samrose** [Holo-Host/nixpkgs#8]

**Comment by gavinrogers** [comment]
This is exactly what we need to do

http://hydra.earthtools.ca/jobset/not-os/notos#tabs-configuration

**Comment by samrose** [comment]
@gavinrogers indeed. Thanks for the example

**Comment by gavinrogers** [comment]
Not-os itself it a good template. I'm going to start creating our own release.nix based upon it. I think we need a new repository, if that's ok with everyone. I'm going to call it Holo-Port/HoloPortOS if that's ok with @samrose @artbrock @neonphog
